### ISSUE TITLE
Is there any plan to support CycloneDDS？

### ISSUE THREAD

**Issue by luxingxiao** [pinorobotics/rtpstalk#1]
CycloneDDS currently uses RTPS 2.1 version, currently rtpstalk only supports 2.2 and 2.3. Is there any plan to support CycloneDDS？

**Comment by lambdaprime** [comment]
Hi @luxingxiao,

Thank you for the message.
Yes we can consider to do this.

Could you please describe your usecase for CycloneDDS. Are you using it as part of Robot Operating System or something else?

**Comment by luxingxiao** [comment]
>

**Comment by luxingxiao** [comment]
Hi @lambdaprime 
Thank you for your reply.
We use CycloneDDS in ROS2.

**Comment by lambdaprime** [comment]
Hi @luxingxiao 

According to [ROS Targeted Platforms](https://www.ros.org/reps/rep-2000.html) document the oldest supported Cyclone DDS version is 0.7.x (Coquette) which is supported by Foxy Fitzroy (EOL is May 2023).
Looking at [Eclipse Cyclone DDS™ 0.7.0 (Coquette) Release Review](https://projects.eclipse.org/projects/iot.cyclonedds/reviews/0.7.0-coquette-release-review) they already support "DDSI specification version 2.3" which is RTPS 2.3 that rtpstalk supports now.

Could you please let us know:
1. What ROS distribution you are using?
1. What version of Cyclone DDS you have?

**Comment by luxingxiao** [comment]
Hi @lambdaprime 

1. The distribution we use for ROS2 is Humble.
2. The CycloneDDS version is 0.10

We have done custom development on the project: [rmw_cyclonedds](https://github.com/ros2/rmw_cyclonedds/ )

**Comment by lambdaprime** [comment]
Hi @luxingxiao 

We added support for CycloneDDS into rtpstalk v4 and latest versions of [jros2client](https://github.com/lambdaprime/jros2client)

Please try it out.

**Comment by luxingxiao** [comment]
> Hi @luxingxiao
> 
> We added support for CycloneDDS into rtpstalk v4 and latest versions of [jros2client](https://github.com/lambdaprime/jros2client)
> 
> Please try it out.

So cool!  I use CycloneDDS as the publisher of HelloworldExample and rtpstalk as the subscriber and the following exception information:

Mismatch between message types. Message directed to reader ENTITYID_UNKNOWN but since current reader message type differs, it is ignored: Data message type mismatch: expected value <class pinorobotics.rtpstalk.impl.RtpsTalkParameterListMessage>, actual value <class pinorobotics.rtpstalk.messages.RtpsTalkDataMessage>

**Comment by lambdaprime** [comment]
Hi @luxingxiao ,

This warning can be ignored

Could you please [enable logging](http://pinoweb.freetzi.com/rtpstalk/Quick_Start.html#Logging) and attach here so we can check. You can try to [debug the flow](http://pinoweb.freetzi.com/rtpstalk/Quick_Start.html#Reader%20flow) yourself if you like

**Comment by luxingxiao** [comment]
[rtpstalk-test.log](https://github.com/pinorobotics/rtpstalk/files/11418200/rtpstalk-test.log)
@lambdaprime Attached file is the log.

Rtpstalk seems to have received the data, but for some unknown reason, the onNext method of Subscriber<RtpsTalkDataMessage> is not triggered.

**Comment by lambdaprime** [comment]
Hi @luxingxiao 

According to [QOS policies matching rules](http://pinoweb.freetzi.com/rtpstalk/Quick_Start.html#QOS%20policies%20matching%20rules) your setup will not work because Reader and Writer reliability is not compatible.

We would recommend to change Writer to RELIABLE:

```
  dds_qos_t *qos = dds_create_qos ();
  dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS(10));
  dds_qset_durability(qos, DDS_DURABILITY_TRANSIENT_LOCAL);
```

and try again.

If it will work then you can open another "issue" for rtpstalk to support BEST_EFFORT reliability (currently it does not).

**Comment by QcoderWho** [comment]
I use cyclonedds-python can receive message from rtpstalk publisher. But when  receive the **ENTITYID_P2P_BUILTIN_PARTICIPANT_MESSAGE_WRITER** msg form other participant, the payload can not be extract due to the serialization type is **CDR_LE**, rtpstalk only support built-in message serialization type is **PL_CDR_LE**. I have read the specifications for DDS-RTPS-v2.1, **ENTITYID_P2P_BUILTIN_PARTICIPANT_MESSAGE_WRITER** msg is liveliness protocol, and built-in message serialization type is **PL_CDR_LE**. Is the message payload wrong? The abnormal 
built-in message like this:

![image](https://github.com/pinorobotics/rtpstalk/assets/28644157/7ea9304c-f9a9-45a1-9ddd-552e4293b461)

Other nomal built-in message like this:
![image](https://github.com/pinorobotics/rtpstalk/assets/28644157/1af5c77d-a4ef-42c0-a504-bb12ad922473)

**Comment by pinorobotics** [comment]
Hi all,

Thank you for reporting the problems.

- Warning problem is moved to Issue #2 and was fixed in **rtpstalk** version 4.
- About CycloneDDS support - it was implemented and already available since version 3.

Closing this issue.
